plugins { id 'com.android.application' }
android {
    namespace 'uz.ijara.bridge'
    compileSdk 35
    defaultConfig {
        applicationId 'uz.ijara.bridge'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
    buildTypes { release { minifyEnabled false } }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {
    implementation 'com.ttlock:ttlock:3.5.7'
    implementation 'com.google.code.gson:gson:2.11.0'
    testImplementation 'junit:junit:4.13.2'
}
